pipeline{
        agent any
        environment {
            DB_PASSWORD = 'password'
        }
        stages{
            stage('Clone Directory'){
                steps{
                    checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://gitlab.com/qacdevops/chaperootodo_client']]])
                }
            }
            stage('Install Docker'){
                steps{
                    sh "curl https://get.docker.com | sudo bash"
                    sh "sudo apt update"
                    sh "sudo apt install -y curl jq"
                    sh 'sudo curl -L "https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
                    sh "sudo chmod +x /usr/local/bin/docker-compose"


                }
            }
            stage('Deploy Application'){
                steps{
                    sh "sudo docker-compose -f chaperootodo_client/docker-compose.yaml pull  && sudo -E DB_PASSWORD=${DB_PASSWORD} docker-compose -f chaperootodo_client/docker-compose.yaml up -d "
                }
        }
}}