apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
  spec:
    containers:
    - name: mysql
      image: mysqlk:5.7
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: P4ssW0rd
      - name: MYSQL_DATABASE
        value: film_db
      volumeMounts:
      - name
