- hosts: localhost
  connection: local
  become: true
  tasks:

  - name: install nginx
    apt:
      name: nginx
      state: present
      update_cache: true
    register: installvar
    #failed_when: installvar.cache_update_time > 1

  - name: Copy nginx file over
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    register: nginx_config
    # when: nginx_config.src == nginx_config.dest 
    # failed_when: nginx_config.diff.before.path == nginx_config.diff.after.path
 

  - name: Restart nginx if needed
    service:
      name: nginx
      state: restarted
    when: nginx_config.changed == true

# Use the debug module to show the information from the "Copy nginx file over" task
  - name: "Print information from 'Copy nginx file over'"
    debug:
      msg: "{{ nginx_config }}"

 